project:
  type: book
  output-dir: _book

book:
  title: "Data Literate with R"
  lang: en
  author: "Nicolas Meseth"
  toc-depth: 1
  chapters:
    - index.qmd
    - documents/data-transformation/select-columns.qmd
    - documents/data-transformation/filter-rows.qmd
    - documents/data-transformation/add-columns.qmd
    
format:
  html:
    theme: cosmo
    code-link: true
    df-print: tibble
  pdf:
    documentclass: scrreprt
    
execute:
  freeze: auto
