project:
  type: book
  output-dir: _book
  
number-sections: true
number-depth: 2
toc-depth: 3

book:
  title: "Data Literate with R"
  lang: en
  author: "Nicolas Meseth"
  toc-depth: 1
  chapters:
    - index.qmd
    
    - part: book-parts/data-transformation.qmd
      chapters:
      - documents/data-transformation/data-transformation-operations.qmd
      - documents/data-transformation/select-columns.qmd
      - documents/data-transformation/filter-rows.qmd
      - documents/data-transformation/add-columns.qmd
      - documents/data-transformation/summarize-rows.qmd
      - documents/data-transformation/sort-rows.qmd
      
    - part: book-parts/data-visualization.qmd
      chapters:
      - documents/data-visualization/data-visualization-overview.qmd
      
format:
  html:
    theme: cosmo
    code-link: true
    df-print: tibble
  pdf:
    documentclass: scrreprt
    
execute:
  freeze: auto
